#!/bin/sh
#$-S /bin/sh
#$-cwd

##################################################################################################
# Description: Perform Zcall. Run SGE batch job for zcall_doCall.sh, output .tped and .tfam files with zcalls.
# if arg4 the threshold file is provided then the calibration step will not be carried out.
# USAGE: qsub -q <queue.q>  sge_zcall paramfile
# ARGS: 
# arg1: parameter file name
# arg2: Z value
# arg3: I value
# arg4: threshold file generated during calibration
# OUTPUT: tped and tfam files with zcalls on the No Call SNPs
##################################################################################################



#args
params=${1}
Z=${2}
I=${3}
tfile=${4}

##need to define path to params file 
cwdir=`pwd`


#source the params file with specified variables req to run jobs 
#source /scratch/project/pipelines/exome_chip/zcall_workflow/ZCALL_PARAMs.sh
source ${cwdir}/${params}


#run job with optimal threshold file
/bin/bash ${cwdir}/zcall_doCall.sh ${params} ${Z} ${I}  ${tfile}

